name: Rust

on:
  push:
    branches: ["dev", "develop", "main", "releases/**"]
  pull_request:
    branches: ["dev", "develop", "main"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # do not skip push on branch starts with releases/
      should_skip: ${{ steps.skip_check.outputs.should_skip == 'true' && !startsWith(github.ref_name, 'releases/') }}

    steps:
      - uses: actions/checkout@v4

      - name: Install cross-compilation tools
        run: |
          sudo apt update
          apt install tree -y 
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            mingw-w64 \
            gcc-x86-64-linux-gnu \
            musl-tools
          
      - name: Install Rust Targets
        run: |
          rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-pc-windows-msvc

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          # GitHub repo token to use to avoid rate limiter
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd easytier
          cargo build --release --target x86_64-unknown-linux-gnu
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Package Binaries
        run: |
          mkdir -p release_binaries
          tree
          cp target/x86_64-unknown-linux-gnu/release/easytier.so release_binaries/easytier-linux-x86_64.so
          cp target/aarch64-unknown-linux-gnu/release/easytier.so release_binaries/easytier-linux-arm64.so
          cp target/x86_64-pc-windows-msvc/release/easytier.dll release_binaries/easytier-win-x86_64.dll

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release_binaries/easytier-linux-x86_64
            release_binaries/easytier-linux-arm64
            release_binaries/easytier-win-x86_64.exe
